### PR TITLE
Cleanup WidgetSDK from most warnings

### PR DESCRIPTION
**Pull request by rasmustautsglia**
**Jira issue:**
https://glia.atlassian.net/browse/MOB-2846

**What was solved?**
WidgetSDK had a lot of warnings that made further development not pleasent. This PR removes most of them. Also some methods had been unavailable for over 6 months and those were deleted

**Release notes:**

 - [ ] Feature
 - [X] Ignore
 - [ ] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

**Additional info:**

 - [ ] Tests fixed, added? Unit, acceptance, snapshots?
 - [ ] Logging necessary for future troubleshooting of customer issues added?

**Screenshots:**

### CODE REVIEW

**Comment by rasmustautsglia** [comment]
!squash

**Review by gersonnoboa — APPROVED** [review]
There's three that appear at the bottom of the files that are super easy, just removing the `Void`. Could you also delete those?

**Comment by rasmustautsglia** [comment]
fixed [431be73](https://github.com/salemove/ios-sdk-widgets/pull/839/commits/431be737c949a9667337229dc8cd649069e23539)

**Review by igorkravchenko — APPROVED** [review]

**Comment by rasmustautsglia** [comment]
!squash

**Pull request merged**
