### PR TITLE
Add styles for text view states on Welcome Message Center screen

### PR DESCRIPTION
**Pull request by igorkravchenko**
Add ability to disable text field.

MOB-1797

### CODE REVIEW

**Review by EgorovEI — APPROVED** [review]

**Review by gersonnoboa — COMMENTED** [review]
There are some SwiftLint issues. Some are old but some are very recent. Do you think you could add a commit to fix them?

**Comment by igorkravchenko** [comment]
> There are some SwiftLint issues. Some are old but some are very recent. Do you think you could add a commit to fix them?

Fixed warnings related to secure messaging 7656eff892a1c47ea748c78655fc76bd38294035.

**Review by gersonnoboa — APPROVED** [review]

**Comment by igorkravchenko** [comment]
!squash

**Comment by igorkravchenko** [comment]
merge!

**Comment by gersonnoboa** [comment]
!merge

**Pull request merged**
