### PR TITLE
Remove SceneDelegate

### PR DESCRIPTION
**Pull request by dukhovnyi**
The project can't use SceneDelegate and AppDelegate at the same time. Removed SceneDelegate to make AppDelegate work and pass necessary events to SalemoveAppDelegate (example applicationDidBecomeActive).

### CODE REVIEW

**Comment by kuldar-daniel** [comment]
Why can't it use both?

**Comment by dukhovnyi** [comment]
> Why can't it use both?

Because if we have an "Application Scene Manifest" in  `Info.plist` and app delegate has a `configurationForConnectingSceneSession` method, the UIApplication doesn't send background and foreground lifecycle messages to our app delegate - `applicationDidBecomeActive` (our case), `applicationWillResignActive`, `applicationDidEnterBackground`, and `applicationWillEnterForeground`.

**Review by kuldar-daniel — APPROVED** [review]

**Review by EgorovEI — APPROVED** [review]

**Review by igorkravchenko — COMMENTED** [review]
Not sure if removing it will help especially when we bump up deployment target to iOS 13. I think we need to ensure that SDK works in expected way with SceneDelegate too.
@dukhovnyi

**Comment by dukhovnyi** [comment]
@igorkravchenko  From a short perspective, we should be sure that TestingApp works correctly, however, from a long perspective we should migrate to using SceneDelegate.

**Review by igorkravchenko — APPROVED** [review]

**Pull request merged**
