### PR TITLE
Fix Cocoapods warning about missed DEPLOYMENT_TARGET value

### PR DESCRIPTION
**Pull request by yurii-glia**

### CODE REVIEW

**Review by rasmustautsglia — APPROVED** [review]

**Review by gersonnoboa — COMMENTED** [review]
What was happening? Where was it happening and how does this fix it?

**Review by igorkravchenko — COMMENTED** [review]
Was it a warning during installation of Cocoapods or during Xcode build phase?

**Comment by yurii-glia** [comment]
During the build, you can see warnings like this:
image
It happens because dependencies have a minimal deployment target by default 9.0, to avoid these warnings we just need to set it to the same deployment target version as we have in our project.
So, this fix should decrease the number of warnings in the project.
@gersonnoboa @igorkravchenko

**Comment by gersonnoboa** [comment]
@yurii-glia it would be good to mention that on the commit message

**Review by EgorovEI — APPROVED** [review]

**Comment by yurii-glia** [comment]
@gersonnoboa  done

**Review by gersonnoboa — APPROVED** [review]

**Comment by yurii-glia** [comment]
!merge

**Pull request merged**
