### PR TITLE
Add company name to live observation confirmation alert message

### PR DESCRIPTION
**Pull request by rasmustautsglia**
This PR adds company name to live observation alert.

MOB-2739

### CODE REVIEW

**Comment by mikktammeglia** [comment]
@rasmustautsglia - In custom locales project there has been just changes implemented for how company name will be used. In case it has passed you by then please check with the custom locales gentlemen how the changes would influence this PR.

**Comment by rasmustautsglia** [comment]
@mikktammeglia Gerson notified me immediately after merging his PR to development, after which I rebased LO branch on development and made my modifications to it :)

**Review by EgorovEI — COMMENTED** [review]
Could you add unit tests?

**Comment by rasmustautsglia** [comment]
Added unit test [da1432f](https://github.com/salemove/ios-sdk-widgets/pull/797/commits/da1432f69b9ad59c2104da032469e49ad7b26b83)

**Review by EgorovEI — APPROVED** [review]

**Review by gersonnoboa — APPROVED** [review]

**Comment by rasmustautsglia** [comment]
!squash

**Pull request merged**
