### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by kuldar-daniel**

### CODE REVIEW

**Review by dukhovnyi — COMMENTED** [review]
Looks ok, but what is the main aim for this README file?

**Comment by kuldar-daniel** [comment]
We had to onboard a new developer and it seems we are missing basic guidelines for getting project up and running. So thought I might as well add one.

**Comment by dukhovnyi** [comment]
@kuldar-daniel  great, my congratulations 🎉
Let's add information about SwiftGen & SwiftLint.

**Comment by VladKupriienko** [comment]
Good point from Yurii, it's good for new devs to know. Other than that, short and to the point.

**Comment by kuldar-daniel** [comment]
Changed according to Yuri's suggestion

**Review by dukhovnyi — APPROVED** [review]

**Review by VladKupriienko — APPROVED** [review]

**Pull request merged**
