### PR TITLE
Fix screen sharing button

### PR DESCRIPTION
**Pull request by rasmustautsglia**
When clicking on end screen share button in call view, nothing happened. This PR fixes the issue.

MOB-1921

### CODE REVIEW

**Review by gersonnoboa — COMMENTED** [review]
What is `in au`? In the commit it says "When clicking on end screen share button in au"

**Comment by rasmustautsglia** [comment]
My bad. A typo

**Comment by rasmustautsglia** [comment]
Changed

**Review by gersonnoboa — APPROVED** [review]

**Comment by rasmustautsglia** [comment]
!merge

**Pull request merged**
