### PR TITLE
Update CoreSDK 1.0.5 dependency

### PR DESCRIPTION
**Pull request by yurii-glia**

### CODE REVIEW

**Review by rasmustautsglia — APPROVED** [review]

**Comment by EgorovEI** [comment]
Do we need to update also the CoreSDK in Package.swift?

**Comment by gersonnoboa** [comment]
When the CI does this, there's more files there. Should those be here too? For example as Egor said, the Package.swift, also the static version that is set in a Swift file, etc.

**Comment by EgorovEI** [comment]
> 

Static version in swift file changes when CI increments WidgetsSDK version, not CoreSDK

**Comment by yurii-glia** [comment]
Core SDK version incrementation happens in this pr - https://github.com/salemove/ios-sdk-widgets/pull/692

**Pull request closed without merging**
