### PR TITLE
Add entry point for EntryWidget for Secure Conversation

### PR DESCRIPTION
**Pull request by ykyivskyi-gl**
MOB-3815

**What was solved?**
This PR adds top banner for Secure Conversation as an Entry Point for Entry Widget that will allow to connect to call

Tests will be added along with parent issue

**Release notes:**

 - [ ] Feature
 - [X] Ignore
 - [ ] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

**Additional info:**

- [ ] Is the feature sufficiently tested? All tests fixed? Necessary unit, acceptance, snapshots added? Check that at least new public classes & methods are covered with unit tests
 - [ ] Did you add logging beneficial for troubleshooting of customer issues?
 - [ ] **Did you add new logging?** We would like the logging between platforms to be similar. Refer to **Logging from iOS SDKs** → **Things to consider for newly added logs** in Confluence for more information.

**Screenshots:**
Screenshot 2024-09-20 at 17 24 55
Screenshot 2024-09-20 at 17 24 55

### CODE REVIEW

**Comment by ykyivskyi-gl** [comment]
!squash

**Review by AndriiHorishniiMOC — APPROVED** [review]
LGTM

**Review by EgorovEI — APPROVED** [review]
Please fix introduced linter warnings

**Comment by ykyivskyi-gl** [comment]
!squash

**Comment by ykyivskyi-gl** [comment]
@EgorovEI Done. For some reason there was no errors for me at the first place.

Also updated snapshots images https://github.com/salemove/ios-widgets-snapshots/pull/85

**Pull request merged**
