### PR TITLE
Fix status for GVA delivered messages

### PR DESCRIPTION
**Pull request by EgorovEI**
Previously the "Delivered" status was displayed for GVA Quick replied messages. Now it works the same way as regular visitor messages. After receiving response for sent single choice option, the outgoing message is replaced with visitor message with "Delivered" status.

MOB-2613

### CODE REVIEW

**Comment by EgorovEI** [comment]
I will try to add tests in separate PR

**Review by igorkravchenko — APPROVED** [review]
@EgorovEI  High chances are there's merge conflict due to my latest changes introduced by send message payload.

**Comment by EgorovEI** [comment]
!squash

**Review by gersonnoboa — APPROVED** [review]

**Review by rasmustautsglia — APPROVED** [review]

**Comment by EgorovEI** [comment]
!squash

**Pull request merged**
