### PR TITLE
[MUIC-468] Fix video bar buttons in portrait mode

### PR DESCRIPTION
**Pull request by KarimovaKarina**
This PR fixes the issue with :
1. Start a two-way video call (or upgrade from chat)
2. Open chat 
3. Open call again from bubble
bar buttons were hidden, back and end buttons were broken.

### CODE REVIEW

**Comment by KarimovaKarina** [comment]
they will be hidden after 3 secs in landscape mode.

**Review by dukhovnyi — APPROVED** [review]
oh, sorry, didn't check all `CallView` class implementation. 
thank you for the clarification 👍

**Comment by KarimovaKarina** [comment]
@VladKupriienko  aaa ok. I tried to reproduce issue from old MUIC-359. But now i understand problem. thank you =)

**Comment by KarimovaKarina** [comment]
@dukhovnyi , @kuldar-daniel  with new commit: when the visitor rotates the phone to landscape view, buttons disappear after 3 seconds. To see the buttons again, then the visitor has to tap on the screen. This behavior happens when you go back to video from chat or from main view by tapping on bubble in landscape mode. It also keeps bar buttons working in portrait mode.

**Review by kuldar-daniel — APPROVED** [review]

**Pull request merged**
