### PR TITLE
Send secure messages from welcome screen

### PR DESCRIPTION
**Pull request by gersonnoboa**
Add possibility to send the send secure messages method from the SDK
using the `Environment`. Success and error handling will come in the
next PR, as well as tests.

I am making this PR so that some common functionality that will be used by Igor is already present in the feature branch. Also, that way the PRs are concise and easier to read. All TODOs are in place not to forget stuff.

MOB-1698

### CODE REVIEW

**Review by igorkravchenko — COMMENTED** [review]
Looks good to me so far 👍

**Review by rasmustautsglia — APPROVED** [review]
Looks good!

**Review by igorkravchenko — APPROVED** [review]
Looks good to me 👍

**Comment by gersonnoboa** [comment]
!merge

**Pull request merged**
